on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: dvershinin/lastversion-action@v0.0.1
        with:
          repository: 'nginx'
      # Use the output from the `hello` step
      - name: Get the NGINX last version
        run: echo "The time was ${{ steps.hello.outputs.last_version }}"
      - name: Download stable NGINX
        id: download-nginx
        uses: dvershinin/lastversion-action@v0.0.1
        with:
          repository: 'nginx'
          action: 'unzip'
          branch: 'stable'
      - name: What do we have here
        run: ls -al
      - name: Download stable Mautic
        id: mautic-lastversion
        uses: dvershinin/lastversion-action@v0.0.1
        with:
          repository: 'mautic/mautic'
          extra_args: '--pre'
      - name: Echo mautic last version
        run: echo "The time was ${{ steps.mautic-lastversion.outputs.last_version }}"
